Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -98,6 +98,7 @@ jobs:
       run: |
         export ${{ github.event.inputs.build_options }} LAN=${{ github.event.inputs.lan_addr }}
         [ ${{ github.event.inputs.ccache }} = 'true' ] && export ENABLE_CCACHE=y
+        [ ${{ github.event.inputs.SquashFS_zstd }} = 'true' ] && export ENABLE_SquashFS_ZSTD=y
         [ -n ${{ github.event.inputs.root_password }} ] && export ROOT_PASSWORD="${{ github.event.inputs.root_password }}"
         bash <(curl -sS https://raw.githubusercontent.com/0118Add/OpenWrt/refs/heads/main/openwrt/build.sh) ${{ env.build_version }} ${{ github.event.inputs.device }}
         cd openwrt
@@ -106,14 +107,14 @@ jobs:
         else
           tags=snapshot-25.12-$(git log -n 1 --date=format:"%Y%m%d" --format="%cd")-$(git log --pretty=format:"%h" -1)
         fi
-        echo "latest_release=$tags" >>$GITHUB_ENV
+        echo "latest_release=${tags}-${{ github.event.inputs.device }}" >>$GITHUB_ENV
 
-    - name: Extensive logs after a failed compilation
-      working-directory: /builder
-      if: steps.compile.outcome == 'failure'
-      run: |
-        cd openwrt
-        make V=s
+    #- name: Extensive logs after a failed compilation
+    #  if: steps.compile.outcome == 'failure'
+    #  working-directory: /builder
+    #  run: |
+    #    cd openwrt
+    #    make -j1 V=s IGNORE_ERRORS="n m"
 
     - name: Delete Cached
       if: ${{ github.event.inputs.ccache == 'true' }}
@@ -140,9 +141,12 @@ jobs:
         if [ "${{ github.event.inputs.device }}" = "x86_64" ]; then
           cp -a openwrt/bin/targets/x86/*/*-ext4-combined-efi.img.gz rom/
           cp -a openwrt/bin/targets/x86/*/*-squashfs-combined-efi.img.gz rom/
+          cp -a openwrt/bin/targets/x86/*/*-squashfs-combined-efi.vmdk rom/
           cp -a openwrt/bin/targets/x86/*/*-generic-rootfs.tar.gz rom/
-          cp -a openwrt/bin/targets/x86/*/*-x86-64-generic.manifest info/manifest.txt
-          cp -a openwrt/bin/targets/x86/*/config.buildinfo info/config.buildinfo
+          cp -a openwrt/bin/targets/x86/*/*-x86-64-generic.manifest rom/manifest.txt
+          cp -a openwrt/bin/targets/x86/*/config.buildinfo rom/config.buildinfo
+          cp -a openwrt/.config rom/config.txt
+          cp -a openwrt/x86_64-kmodpkg.tar.gz rom/ || echo "Kmod archive not found"
           cd rom && sha256sum *gz > ../info/sha256sums.txt
         elif [ "${{ github.event.inputs.device }}" = "armv8" ]; then
           tar zcf rom/u-boot-qemu_armv8.tar.gz -C openwrt/bin/targets/armsr/armv8*/ ./u-boot-qemu_armv8
@@ -151,8 +155,8 @@ jobs:
           cp -a openwrt/bin/targets/armsr/armv8*/*-generic-ext4-combined-efi.img.gz rom/
           cp -a openwrt/bin/targets/armsr/armv8*/*-generic-squashfs-combined-efi.img.gz rom/
           cp -a openwrt/bin/targets/armsr/armv8*/*-rootfs.tar.gz rom/
-          cp -a openwrt/bin/targets/armsr/armv8*/*.manifest info/manifest.txt
-          cp -a openwrt/bin/targets/armsr/armv8*/config.buildinfo info/config.buildinfo
+          cp -a openwrt/bin/targets/armsr/armv8*/*.manifest rom/manifest.txt
+          cp -a openwrt/bin/targets/armsr/armv8*/config.buildinfo rom/config.buildinfo
           cd rom && sha256sum * > ../info/sha256sums.txt
         fi
     - name: Upload artifacts
